### ISSUE TITLE
CLI: create team "my-team" does not work as expected, command hangs

### ISSUE THREAD

**Issue by ianroy-opslevel** [OpsLevel/cli#166]
## Expected Outcome:

`opslevel create team "my-team"` creates a team

## Actual Outcome:

`opslevel create team "my-team"` command hangs and does not do anything

## Other Observations:

The following commands work:
```
cat << EOF | opslevel create team "adams-team" -f -
group:
  alias: "core"
responsibilities: "all the things"
EOF
```

```
echo | opslevel create team "my-team" -f -
```

## opslevel-cli version:
```
{
    "version": "2023.9.12",
    "git": "c9c2b4af0934",
    "go": {
        "version": "go1.21.0",
        "compiler": "gc",
        "os": "darwin",
        "arch": "arm64"
    },
    "opslevel": {
        "app_commit": "cb89c9101f17",
        "app_version": "2023-09-12_16-17-35+00-00"
    }
}
```

**Comment by rocktavious** [comment]
The RC for this is likely that we are hanging reading from stdin when a customer just uses `opslevel create team "my-team"`

**Comment by davidbloss** [comment]
@ianroy-opslevel
`opslevel create service "my-team"` and
`opslevel create team "my-team"` are two different commands with different expected inputs.

Calling this out since the title of this issue and the working commands in the **Other Observations** section seem focused on `opslevel create team ...` - but the **Expected/Actual Outcome** sections are focused on `opslevel create service ...`

@rocktavious `opslevel create team "my-team"` creates a team as is

**Comment by ianroy-opslevel** [comment]
@davidbloss I hastily copied in the wrong commands, I'll update the original issue details to reference `opslevel create team` correctly.

**Comment by ianroy-opslevel** [comment]
> @rocktavious `opslevel create team "my-team"` creates a team as is

What version of opslevel-cli are you using?

**Comment by davidbloss** [comment]
@ianroy-opslevel I was using an old version and it looks like something needs to be undone / fixed in the latest version

**Comment by davidbloss** [comment]
[Added a check](https://github.com/OpsLevel/cli/pull/167) that prints a message to users when the command line is waiting for them to manually enter some input.
